version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit test
          command: npm run test:unit
      - run:
          name: code-coverage
          command: npm run test:coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results